version: '3'
networks:
  monitor-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-1
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    user: root
    networks:
      - monitor-net
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager-1
    restart: unless-stopped
    expose:
      - 9093
    ports:
      - "9093:9093"
    networks:
      - monitor-net
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

#  nodeexporter:
#    image: prom/node-exporter:v1.8.0
#    container_name: nodeexporter-1
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.rootfs=/rootfs'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#    restart: unless-stopped
#    expose:
#      - 9100
#    networks:
#      - monitor-net

  prometheus-alert:
    image: feiyu563/prometheus-alert:latest
    container_name: prometheus-alert
    restart: always
    ports:
      - "9094:8080"
    expose:
      - 9094
    networks:
      - monitor-net
    volumes:
      - ./prometheus-alert/db:/app/db
    environment:
      - PA_LOGIN_USER=admin
      - PA_LOGIN_PASSWORD=admin
      - PA_TITLE=prometheusAlert
      - PA_OPEN_FEISHU=1
      - PA_OPEN_DINGDING=0
      - PA_OPEN_WEIXIN=0